import type { ObjectId } from "mongodb";
import type { Capability, CapabilityPolicy, CapabilityPolicyScope, CatalogImportItem, CatalogImportItemOutcome, CatalogImportItemStatus, CatalogReview, CatalogReviewStatus, CatalogReviewSubject, CatalogSyncCounts, CatalogSyncRun, CatalogSnapshotAssessment, CatalogSyncRunStatus, CatalogSyncTrigger, Company, CompanyCandidate, ExternalFleetIdentity, ExternalVehicleIdentity, Fleet, ProviderConnection, Vehicle, VehicleIdentityCapabilityStates, VehicleIdentityPresence } from "@/domain/catalog";

export type CompanyDocument = { _id?: ObjectId; schemaVersion: number; id: string; organizationId: string; name: string; createdAt: Date; updatedAt: Date };
export type FleetDocument = { _id?: ObjectId; schemaVersion: number; id: string; companyId: string; name: string; kind: "standard" | "unassigned"; createdAt: Date; updatedAt: Date };
export type VehicleDocument = { _id?: ObjectId; schemaVersion: number; id: string; companyId: string; origin: "native" | "provider"; placement: { fleetId: string; source: "system" | "admin" }; label?: string; plate?: string; internalCode?: string; createdAt: Date; updatedAt: Date };
export type CompanyCandidateDocument = { _id?: ObjectId; schemaVersion: number; id: string; organizationId: string; connectionId: string; normalizedLabel: string; companyId?: string; createdAt: Date; updatedAt: Date };
export type ProviderConnectionDocument = { _id?: ObjectId; schemaVersion: number; id: string; organizationId: string; credentialRef: string; companyId?: string; authorizedExternalCompanyLabels?: string[]; authorizedExternalFleetIds?: string[]; authorizedExternalVehicleIds?: string[]; createdAt: Date; updatedAt: Date };

export function toCompanyDomain({ id, organizationId, name }: CompanyDocument): Company { return { id, organizationId, name }; }
export function toCompanyDocument(company: Company, now: Date, existing?: CompanyDocument): CompanyDocument { return { schemaVersion: 1, ...company, createdAt: existing?.createdAt ?? now, updatedAt: now }; }
export function toFleetDomain({ id, companyId, name, kind }: FleetDocument): Fleet { return { id, companyId, name, kind }; }
export function toFleetDocument(fleet: Fleet, now: Date, existing?: FleetDocument): FleetDocument { return { schemaVersion: 1, ...fleet, createdAt: existing?.createdAt ?? now, updatedAt: now }; }
export function toVehicleDomain({ id, companyId, origin, placement, label, plate, internalCode }: VehicleDocument): Vehicle { return { id, companyId, origin, placement, ...(label !== undefined ? { label } : {}), ...(plate !== undefined ? { plate } : {}), ...(internalCode !== undefined ? { internalCode } : {}) }; }
export function toVehicleDocument({ label, plate, internalCode, ...vehicle }: Vehicle, now: Date, existing?: VehicleDocument): VehicleDocument { return { schemaVersion: 1, ...vehicle, ...(label !== undefined ? { label } : {}), ...(plate !== undefined ? { plate } : {}), ...(internalCode !== undefined ? { internalCode } : {}), createdAt: existing?.createdAt ?? now, updatedAt: now }; }
export function toCompanyCandidateDomain({ id, organizationId, connectionId, normalizedLabel, companyId }: CompanyCandidateDocument): CompanyCandidate { return { id, organizationId, connectionId, normalizedLabel, ...(companyId !== undefined ? { companyId } : {}) }; }
export function toCompanyCandidateDocument({ companyId, ...candidate }: CompanyCandidate, now: Date, existing?: CompanyCandidateDocument): CompanyCandidateDocument { return { schemaVersion: 1, ...candidate, ...(companyId !== undefined ? { companyId } : {}), createdAt: existing?.createdAt ?? now, updatedAt: now }; }
export function toProviderConnectionDomain({ id, organizationId, credentialRef, companyId, authorizedExternalCompanyLabels, authorizedExternalFleetIds, authorizedExternalVehicleIds }: ProviderConnectionDocument): ProviderConnection { return { id, organizationId, credentialRef, ...(companyId !== undefined ? { companyId } : {}), ...(authorizedExternalCompanyLabels !== undefined ? { authorizedExternalCompanyLabels } : {}), ...(authorizedExternalFleetIds !== undefined ? { authorizedExternalFleetIds } : {}), ...(authorizedExternalVehicleIds !== undefined ? { authorizedExternalVehicleIds } : {}) }; }
export function toProviderConnectionDocument(connection: ProviderConnection, now: Date, existing?: ProviderConnectionDocument): ProviderConnectionDocument { return { schemaVersion: 1, ...connection, createdAt: existing?.createdAt ?? now, updatedAt: now }; }

export type ExternalFleetIdentityDocument = { _id?: ObjectId; schemaVersion: number; id: string; organizationId: string; connectionId: string; entityKind: "fleet"; externalId: string; label: string; fleetId?: string; createdAt: Date; updatedAt: Date };
export type ExternalVehicleIdentityDocument = { _id?: ObjectId; schemaVersion: number; id: string; organizationId: string; connectionId: string; entityKind: "vehicle"; externalId: string; vehicleId?: string; lastSeenRunId?: string; presence?: VehicleIdentityPresence; capabilityStates?: VehicleIdentityCapabilityStates; createdAt: Date; updatedAt: Date };

export function toExternalFleetIdentityDomain({ id, organizationId, connectionId, entityKind, externalId, label, fleetId }: ExternalFleetIdentityDocument): ExternalFleetIdentity { return { id, organizationId, connectionId, entityKind, externalId, label, ...(fleetId !== undefined ? { fleetId } : {}) }; }
export function toExternalFleetIdentityDocument({ fleetId, ...identity }: ExternalFleetIdentity, now: Date, existing?: ExternalFleetIdentityDocument): ExternalFleetIdentityDocument { return { schemaVersion: 1, ...identity, ...(fleetId !== undefined ? { fleetId } : {}), createdAt: existing?.createdAt ?? now, updatedAt: now }; }
export function toExternalVehicleIdentityDomain({ id, organizationId, connectionId, entityKind, externalId, vehicleId, lastSeenRunId, presence, capabilityStates }: ExternalVehicleIdentityDocument): ExternalVehicleIdentity { return { id, organizationId, connectionId, entityKind, externalId, ...(vehicleId !== undefined ? { vehicleId } : {}), ...(lastSeenRunId !== undefined ? { lastSeenRunId } : {}), ...(presence !== undefined ? { presence } : {}), ...(capabilityStates !== undefined ? { capabilityStates } : {}) }; }
export function toExternalVehicleIdentityDocument({ vehicleId, lastSeenRunId, presence, capabilityStates, ...identity }: ExternalVehicleIdentity, now: Date, existing?: ExternalVehicleIdentityDocument): ExternalVehicleIdentityDocument { return { schemaVersion: 1, ...identity, ...(vehicleId !== undefined ? { vehicleId } : {}), ...(lastSeenRunId !== undefined ? { lastSeenRunId } : {}), ...(presence !== undefined ? { presence } : {}), ...(capabilityStates !== undefined ? { capabilityStates } : {}), createdAt: existing?.createdAt ?? now, updatedAt: now }; }

export type CatalogReviewDocument = { _id?: ObjectId; schemaVersion: number; id: string; organizationId: string; connectionId: string; companyId: string; subject: CatalogReviewSubject; externalId: string; status: CatalogReviewStatus; label?: string; candidateFleetIds?: string[]; resolvedFleetId?: string; normalizedPlate?: string; candidateVehicleIds?: string[]; resolvedVehicleId?: string; createdAt: Date; updatedAt: Date };
export type CapabilityPolicyDocument = { _id?: ObjectId; schemaVersion: number; id: string; organizationId: string; scope: CapabilityPolicyScope; scopeId: string; capability: Capability; sourceOrder: string[]; createdAt: Date; updatedAt: Date };

export function toCatalogReviewDomain(document: CatalogReviewDocument): CatalogReview {
  const { id, organizationId, connectionId, companyId, externalId, status } = document;
  if (document.subject === "fleet-binding") {
    return { id, organizationId, connectionId, companyId, externalId, status, subject: "fleet-binding", label: document.label as string, candidateFleetIds: document.candidateFleetIds ?? [], ...(document.resolvedFleetId !== undefined ? { resolvedFleetId: document.resolvedFleetId } : {}) };
  }
  return { id, organizationId, connectionId, companyId, externalId, status, subject: "vehicle-match", normalizedPlate: document.normalizedPlate as string, candidateVehicleIds: document.candidateVehicleIds ?? [], ...(document.resolvedVehicleId !== undefined ? { resolvedVehicleId: document.resolvedVehicleId } : {}) };
}
export function toCatalogReviewDocument(review: CatalogReview, now: Date, existing?: CatalogReviewDocument): CatalogReviewDocument {
  const base = { schemaVersion: 1 as const, id: review.id, organizationId: review.organizationId, connectionId: review.connectionId, companyId: review.companyId, externalId: review.externalId, subject: review.subject, status: review.status, createdAt: existing?.createdAt ?? now, updatedAt: now };
  if (review.subject === "fleet-binding") {
    return { ...base, label: review.label, candidateFleetIds: review.candidateFleetIds, ...(review.resolvedFleetId !== undefined ? { resolvedFleetId: review.resolvedFleetId } : {}) };
  }
  return { ...base, normalizedPlate: review.normalizedPlate, candidateVehicleIds: review.candidateVehicleIds, ...(review.resolvedVehicleId !== undefined ? { resolvedVehicleId: review.resolvedVehicleId } : {}) };
}
export function toCapabilityPolicyDomain({ id, organizationId, scope, scopeId, capability, sourceOrder }: CapabilityPolicyDocument): CapabilityPolicy { return { id, organizationId, scope, scopeId, capability, sourceOrder }; }
export function toCapabilityPolicyDocument(policy: CapabilityPolicy, now: Date, existing?: CapabilityPolicyDocument): CapabilityPolicyDocument { return { schemaVersion: 1, ...policy, sourceOrder: [...policy.sourceOrder], createdAt: existing?.createdAt ?? now, updatedAt: now }; }

export type CatalogImportItemDocument = { _id?: ObjectId; schemaVersion: number; id: string; organizationId: string; connectionId: string; runId: string; externalId: string; status: CatalogImportItemStatus; outcome?: CatalogImportItemOutcome; createdAt: Date; updatedAt: Date };

export function toCatalogImportItemDomain({ id, organizationId, connectionId, runId, externalId, status, outcome }: CatalogImportItemDocument): CatalogImportItem { return { id, organizationId, connectionId, runId, externalId, status, ...(outcome !== undefined ? { outcome } : {}) }; }
export function toCatalogImportItemDocument({ outcome, ...item }: CatalogImportItem, now: Date, existing?: CatalogImportItemDocument): CatalogImportItemDocument { return { schemaVersion: 1, ...item, ...(outcome !== undefined ? { outcome } : {}), createdAt: existing?.createdAt ?? now, updatedAt: now }; }

export type CatalogSyncRunDocument = { _id?: ObjectId; schemaVersion: number; id: string; organizationId: string; connectionId: string; trigger: CatalogSyncTrigger; status: CatalogSyncRunStatus; fullSnapshot: boolean; startedAt: Date; completedAt?: Date; checkpoint?: string; counts: CatalogSyncCounts; snapshot?: CatalogSnapshotAssessment; failureSummary?: string; createdAt: Date; updatedAt: Date };
export type CatalogSyncLeaseDocument = { _id?: ObjectId; schemaVersion: number; organizationId: string; connectionId: string; runId: string; leaseUntil: Date; createdAt: Date; updatedAt: Date };

export function toCatalogSyncRunDomain({ id, organizationId, connectionId, trigger, status, fullSnapshot, startedAt, completedAt, checkpoint, counts, snapshot, failureSummary }: CatalogSyncRunDocument): CatalogSyncRun { return { id, organizationId, connectionId, trigger, status, fullSnapshot, startedAt, counts, ...(completedAt !== undefined ? { completedAt } : {}), ...(checkpoint !== undefined ? { checkpoint } : {}), ...(snapshot !== undefined ? { snapshot } : {}), ...(failureSummary !== undefined ? { failureSummary } : {}) }; }
export function toCatalogSyncRunDocument({ completedAt, checkpoint, failureSummary, ...run }: CatalogSyncRun, now: Date, existing?: CatalogSyncRunDocument): CatalogSyncRunDocument { return { schemaVersion: 1, ...run, ...(completedAt !== undefined ? { completedAt } : {}), ...(checkpoint !== undefined ? { checkpoint } : {}), ...(failureSummary !== undefined ? { failureSummary } : {}), createdAt: existing?.createdAt ?? now, updatedAt: now }; }
