import type { Document } from "mongodb";
import { MAX_REVIEW_CANDIDATES } from "@/domain/catalog";

const objectId = { bsonType: "objectId" };
const version = { bsonType: "int" };
const date = { bsonType: "date" };
const text = { bsonType: "string" };
const boundedIdList = { bsonType: "array", maxItems: MAX_REVIEW_CANDIDATES, items: text };
const capabilityStatus = { enum: ["eligible", "absent", "unsupported", "stale", "unavailable"] };
const capabilityStates = { bsonType: "object", additionalProperties: false, properties: { gps: capabilityStatus, operationalAlerts: capabilityStatus, video: capabilityStatus, videoAlerts: capabilityStatus } };

export const catalogValidators: Record<string, Document> = {
  companies: { $jsonSchema: { bsonType: "object", additionalProperties: false, required: ["_id", "schemaVersion", "id", "organizationId", "name", "createdAt", "updatedAt"], properties: { _id: objectId, schemaVersion: version, id: text, organizationId: text, name: text, createdAt: date, updatedAt: date } } },
  fleets: { $jsonSchema: { bsonType: "object", additionalProperties: false, required: ["_id", "schemaVersion", "id", "companyId", "name", "kind", "createdAt", "updatedAt"], properties: { _id: objectId, schemaVersion: version, id: text, companyId: text, name: text, kind: { enum: ["standard", "unassigned"] }, createdAt: date, updatedAt: date } } },
  vehicles: { $jsonSchema: { bsonType: "object", additionalProperties: false, required: ["_id", "schemaVersion", "id", "companyId", "origin", "placement", "createdAt", "updatedAt"], properties: { _id: objectId, schemaVersion: version, id: text, companyId: text, origin: { enum: ["native", "provider"] }, placement: { bsonType: "object", additionalProperties: false, required: ["fleetId", "source"], properties: { fleetId: text, source: { enum: ["system", "admin"] } } }, label: text, plate: text, internalCode: text, createdAt: date, updatedAt: date } } },
  company_candidates: { $jsonSchema: { bsonType: "object", additionalProperties: false, required: ["_id", "schemaVersion", "id", "organizationId", "connectionId", "normalizedLabel", "createdAt", "updatedAt"], properties: { _id: objectId, schemaVersion: version, id: text, organizationId: text, connectionId: text, normalizedLabel: text, companyId: text, createdAt: date, updatedAt: date } } },
  provider_connections: { $jsonSchema: { bsonType: "object", additionalProperties: false, required: ["_id", "schemaVersion", "id", "organizationId", "credentialRef", "createdAt", "updatedAt"], properties: { _id: objectId, schemaVersion: version, id: text, organizationId: text, credentialRef: text, createdAt: date, updatedAt: date } } },
  external_fleet_identities: { $jsonSchema: { bsonType: "object", additionalProperties: false, required: ["_id", "schemaVersion", "id", "organizationId", "connectionId", "entityKind", "externalId", "label", "createdAt", "updatedAt"], properties: { _id: objectId, schemaVersion: version, id: text, organizationId: text, connectionId: text, entityKind: { enum: ["fleet"] }, externalId: text, label: text, fleetId: text, createdAt: date, updatedAt: date } } },
  external_vehicle_identities: { $jsonSchema: { bsonType: "object", additionalProperties: false, required: ["_id", "schemaVersion", "id", "organizationId", "connectionId", "entityKind", "externalId", "createdAt", "updatedAt"], properties: { _id: objectId, schemaVersion: version, id: text, organizationId: text, connectionId: text, entityKind: { enum: ["vehicle"] }, externalId: text, vehicleId: text, lastSeenRunId: text, presence: { enum: ["present", "absent"] }, capabilityStates, createdAt: date, updatedAt: date } } },
  catalog_reviews: { $jsonSchema: { bsonType: "object", additionalProperties: false, required: ["_id", "schemaVersion", "id", "organizationId", "connectionId", "companyId", "subject", "externalId", "status", "createdAt", "updatedAt"], properties: { _id: objectId, schemaVersion: version, id: text, organizationId: text, connectionId: text, companyId: text, subject: { enum: ["fleet-binding", "vehicle-match"] }, externalId: text, status: { enum: ["pending", "resolved"] }, label: text, candidateFleetIds: boundedIdList, resolvedFleetId: text, normalizedPlate: text, candidateVehicleIds: boundedIdList, resolvedVehicleId: text, createdAt: date, updatedAt: date } } },
  capability_policies: { $jsonSchema: { bsonType: "object", additionalProperties: false, required: ["_id", "schemaVersion", "id", "organizationId", "scope", "scopeId", "capability", "sourceOrder", "createdAt", "updatedAt"], properties: { _id: objectId, schemaVersion: version, id: text, organizationId: text, scope: { enum: ["vehicle", "fleet", "company", "organization"] }, scopeId: text, capability: { enum: ["gps", "operationalAlerts", "video", "videoAlerts"] }, sourceOrder: { bsonType: "array", items: text }, createdAt: date, updatedAt: date } } },
  catalog_import_items: { $jsonSchema: { bsonType: "object", additionalProperties: false, required: ["_id", "schemaVersion", "id", "organizationId", "connectionId", "runId", "externalId", "status", "createdAt", "updatedAt"], properties: { _id: objectId, schemaVersion: version, id: text, organizationId: text, connectionId: text, runId: text, externalId: text, status: { enum: ["pending", "processed"] }, outcome: { enum: ["created", "linked", "reviewed", "rejected"] }, createdAt: date, updatedAt: date } } },
};
