export type CatalogSyncTrigger = "initial" | "scheduled" | "manual";
export type CatalogSyncRunStatus = "active" | "succeeded" | "failed";
export type SnapshotReason = "retrieval-unproven" | "pagination-unproven" | "parse-quality-below-threshold" | "unexpected-empty" | "population-decline";
export const MIN_PARSE_QUALITY_RATIO = 0.98;
export const MIN_POPULATION_RATIO = 0.9;
export type CatalogSnapshotEvidence = { retrievalComplete: boolean; paginationComplete: boolean; receivedRecordCount: number; parseableRecordCount: number };
export type CatalogSnapshotAssessment = CatalogSnapshotEvidence & { authorizedCandidateCount: number; status: "complete" | "partial"; reason?: SnapshotReason };
export type CatalogSyncCounts = { processed: number; created: number; linked: number; reviewed: number; rejected: number; absent: number };
export type CatalogSyncRun = { id: string; organizationId: string; connectionId: string; trigger: CatalogSyncTrigger; status: CatalogSyncRunStatus; fullSnapshot: boolean; startedAt: Date; completedAt?: Date; checkpoint?: string; counts: CatalogSyncCounts; failureSummary?: string; snapshot?: CatalogSnapshotAssessment };
const ZERO_COUNTS: CatalogSyncCounts = { processed: 0, created: 0, linked: 0, reviewed: 0, rejected: 0, absent: 0 };
export type CatalogSyncFailureCategory = "authentication" | "connectivity" | "invalid-response" | "timeout" | "rate-limited" | "internal";
export type CatalogSyncFailure = { category: CatalogSyncFailureCategory; httpStatus?: number; providerErrorCode?: string };
const FAILURE_CATEGORY_LABEL: Record<CatalogSyncFailureCategory, string> = { authentication: "Authentication failed", connectivity: "Provider connection unreachable", "invalid-response": "Provider returned an invalid response", timeout: "Provider request timed out", "rate-limited": "Provider rate limit exceeded", internal: "Internal synchronization error" };
const PROVIDER_ERROR_CODE_PATTERN = /^[A-Za-z0-9_-]{1,40}$/;
function composeFailureSummary({ category, httpStatus, providerErrorCode }: CatalogSyncFailure): string { const code = providerErrorCode !== undefined && PROVIDER_ERROR_CODE_PATTERN.test(providerErrorCode) ? providerErrorCode : undefined; return [FAILURE_CATEGORY_LABEL[category], ...(httpStatus !== undefined ? [`HTTP ${httpStatus}`] : []), ...(code !== undefined ? [`code ${code}`] : [])].join(" - "); }
export function assessCatalogSnapshot(evidence: CatalogSnapshotEvidence | undefined, authorizedCandidateCount: number, priorConfirmed?: CatalogSyncRun): CatalogSnapshotAssessment { const safe = evidence ?? { retrievalComplete: false, paginationComplete: false, receivedRecordCount: 0, parseableRecordCount: 0 }; const partial = (reason: SnapshotReason): CatalogSnapshotAssessment => ({ ...safe, authorizedCandidateCount, status: "partial", reason }); if (!evidence || !safe.retrievalComplete) return partial("retrieval-unproven"); if (!safe.paginationComplete) return partial("pagination-unproven"); if (safe.receivedRecordCount > 0 && safe.parseableRecordCount / safe.receivedRecordCount < MIN_PARSE_QUALITY_RATIO) return partial("parse-quality-below-threshold"); if ((priorConfirmed?.snapshot?.authorizedCandidateCount ?? 0) > 0 && safe.receivedRecordCount === 0) return partial("unexpected-empty"); const baseline = priorConfirmed?.snapshot?.authorizedCandidateCount; if (baseline !== undefined && authorizedCandidateCount < baseline * MIN_POPULATION_RATIO) return partial("population-decline"); return { ...safe, authorizedCandidateCount, status: "complete" }; }
export function startCatalogSyncRun(id: string, params: { organizationId: string; connectionId: string; trigger: CatalogSyncTrigger; fullSnapshot: boolean; snapshot?: CatalogSnapshotAssessment }, startedAt: Date): CatalogSyncRun { return { id, ...params, status: "active", startedAt, counts: { ...ZERO_COUNTS } }; }
export function succeedCatalogSyncRun(run: CatalogSyncRun, completedAt: Date, counts: CatalogSyncCounts): CatalogSyncRun { return { ...run, status: "succeeded", completedAt, counts }; }
export function failCatalogSyncRun(run: CatalogSyncRun, completedAt: Date, failure: CatalogSyncFailure): CatalogSyncRun { return { ...run, status: "failed", completedAt, failureSummary: composeFailureSummary(failure) }; }
export const CATALOG_SYNC_FRESHNESS_WINDOW_MS = 6 * 60 * 60 * 1000;
export function isCatalogSyncDue(lastSuccessAt: Date | undefined, now: Date, freshnessWindowMs: number = CATALOG_SYNC_FRESHNESS_WINDOW_MS): boolean { return lastSuccessAt === undefined || now.getTime() - lastSuccessAt.getTime() >= freshnessWindowMs; }
export function isConfirmedCatalogSnapshot(run: CatalogSyncRun): boolean { return run.status === "succeeded" && run.fullSnapshot && run.snapshot?.status === "complete"; }
export function shouldReconcileCatalogSyncAbsence(run: CatalogSyncRun, priorConfirmed?: CatalogSyncRun): boolean { return isConfirmedCatalogSnapshot(run) && priorConfirmed !== undefined; }
